Repository jenkins-zh/jenkins-cli, pull requests merged in 2019-11, with the labels that each got.

#206 Add support to edit a pipeline from multi-methods
  Makefile
  app/cmd/center_download.go
  app/cmd/center_download_test.go
  app/cmd/common.go
  app/cmd/completion_test.go
  app/cmd/job.go
  app/cmd/job_artifact_test.go
  app/cmd/job_create_test.go
  app/cmd/job_delete_test.go
  app/cmd/job_edit.go
  app/cmd/job_edit_test.go
  app/cmd/job_history.go
  app/cmd/job_input.go
  app/cmd/job_input_test.go
  app/cmd/plugin_upgrade.go
  app/cmd/restart_test.go
  client/artifacts.go
  client/artifacts_test.go
  client/artifacts_test_common.go
  client/core_test.go
  client/core_test_common.go
  client/job.go
  client/job_test.go
  client/job_test_common.go
  client/pluginApi.go
  client/pluginApi_test_common.go
  client/requestmatcher.go
  client/requestmatcher_test.go
  client/status_test.go
  client/status_test_common.go
  client/test_methods.go
  client/user.go
  client/user_test.go
  client/user_test_common.go
  go.mod
  go.sum
  util/http.go
  util/http_test.go
  util/padding.go
Labels: Hacktoberfest, feature

#220 Add support to load a jenkinsfile from url
  app/cmd/job_edit.go
  app/cmd/job_edit_test.go
Labels: feature

#221 Add support to download Jenkins from a mirror site
  app/cmd/center_download.go
  app/cmd/center_download_test.go
  app/cmd/config.go
  app/cmd/config_generate.go
  app/cmd/config_test.go
  client/updateCenter.go
  client/updateCenter_test.go
Labels: feature

#223 Improve test coverages
  app/cmd/center.go
  app/cmd/center_download.go
  app/cmd/center_upgrade.go
  app/cmd/job_artifact.go
  app/cmd/job_artifact_download.go
  app/cmd/job_create.go
  app/cmd/job_delete.go
  app/cmd/job_edit.go
  app/cmd/job_search.go
  app/cmd/job_stop.go
  app/cmd/job_type.go
  app/cmd/plugin_search.go
  app/cmd/plugin_trend.go
  app/cmd/plugin_uninstall.go
  app/cmd/plugin_uninstall_test.go
  app/cmd/plugin_upgrade.go
  app/cmd/queue_cancel.go
  app/cmd/queue_list.go
  app/cmd/user_token.go
  app/helper/error.go
Labels: chore

#222 Add support to download a plugin from mirror site
  app/cmd/center_download.go
  app/cmd/config.go
  app/cmd/plugin_download.go
  app/cmd/plugin_download_test.go
  app/cmd/root.go
  client/core.go
  client/pluginApi.go
  client/pluginApi_test.go
  client/pluginApi_test_common.go
  go.mod
  go.sum
  util/logger.go
  util/logger_test.go
Labels: feature

#224 Add test cases for plugin check
  app/cmd/plugin.go
  app/cmd/plugin_check.go
  app/cmd/plugin_checkout_test.go
  app/cmd/plugin_open.go
  app/cmd/user.go
  client/common.go
  client/pluginApi_test_common.go
  client/pluginManager_test.go
  client/pluginManger.go
Labels: chore

#227 Add more check item about git branch stragtegy
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#211 Add support to install a specific version of plugin
  client/pluginManager_test.go
  client/pluginManger.go
  client/test_methods.go
Labels: Hacktoberfest, enhancement

#232 Add test cases for job param
  app/cmd/config_list.go
  app/cmd/config_list_test.go
  app/cmd/crumbIssuer.go
  app/cmd/crumbissuer_test.go
  app/cmd/job_create.go
  app/cmd/job_log.go
  app/cmd/job_log_test.go
  app/cmd/job_param.go
  app/cmd/job_param_test.go
  app/cmd/plugin_install.go
  app/cmd/plugin_install_test.go
  app/cmd/plugin_list.go
  app/cmd/plugin_upload.go
  client/common_test.go
  client/common_test_common.go
  client/job.go
  client/job_test.go
  client/job_test_common.go
  client/pluginApi.go
  client/pluginApi_test_common.go
  client/pluginManager_test.go
  client/pluginManger.go
  client/test_methods.go
  util/http.go
Labels: test

#169 Add support to diagnose configurations
  app/cmd/doctor.go
  app/cmd/doctor_test.go
  app/cmd/plugin_list.go
  app/cmd/plugin_list_test.go
  app/cmd/plugin_search.go
  app/cmd/plugin_search_test.go
  app/cmd/plugin_upgrade.go
  client/pluginApi.go
  client/pluginManager_test.go
  client/pluginManger.go
  client/test_methods.go
Labels: feature

#240 Add support to download a specific Jenkins war
  app/cmd/center_download.go
  app/cmd/config.go
  app/cmd/config_generate.go
  app/cmd/config_generate_test.go
  app/cmd/config_test.go
  app/cmd/plugin_install_test.go
  app/cmd/plugin_uninstall_test.go
  app/cmd/user_delete_test.go
  app/cmd/user_test.go
  app/cmd/user_token_test.go
  app/helper/error.go
  app/helper/error_test.go
  app/helper/setup_test.go
  client/updateCenter.go
  client/updateCenter_test.go
  go.mod
  go.sum
Labels: feature

#242 Add bash completion support to plugin, config and job cmd
  app/cmd/common.go
  app/cmd/config_list.go
  app/cmd/job_search.go
  app/cmd/open.go
  app/cmd/plugin_list.go
  app/cmd/plugin_list_test.go
  app/cmd/plugin_search.go
  app/cmd/plugin_upgrade.go
  app/cmd/queue_list.go
  app/cmd/queue_list_test.go
  app/cmd/root.go
  client/artifacts.go
  client/artifacts_test_common.go
  client/job.go
  client/job_test.go
  util/table.go
Labels: feature

#246 Add cmd completion for config select and remove
  app/cmd/root.go
Labels: feature

#245 Add i18n support for command description
  .gitignore
  Makefile
  app/cmd/center.go
  app/cmd/center_download.go
  app/cmd/center_upgrade.go
  app/cmd/center_watch.go
  app/cmd/common.go
  app/cmd/completion.go
  app/cmd/config.go
  app/cmd/config_add.go
  app/cmd/config_edit.go
  app/cmd/config_generate.go
  app/cmd/config_list.go
  app/cmd/config_remove.go
  app/cmd/doc.go
  app/cmd/job_artifact.go
  app/cmd/plugin.go
  app/cmd/plugin_download.go
  app/cmd/plugin_install.go
  app/cmd/plugin_list.go
  app/cmd/plugin_search.go
  app/cmd/plugin_uninstall.go
  app/cmd/plugin_upgrade.go
  app/cmd/plugin_upload.go
  app/cmd/queue.go
  app/cmd/restart.go
  app/cmd/root.go
  app/i18n/i18n.go
  app/i18n/i18n_test.go
  app/i18n/jcli/zh_CN/LC_MESSAGES/jcli.po
  app/i18n/setup_test.go
  app/version.go
  go.mod
  go.sum
  i18n.md
Labels: feature

#248 Add support to stop the last build
  app/cmd/job.go
  app/cmd/job_artifact_download.go
  app/cmd/job_build.go
  app/cmd/job_create.go
  app/cmd/job_delete.go
  app/cmd/job_edit.go
  app/cmd/job_history.go
  app/cmd/job_input.go
  app/cmd/job_input_test.go
  app/cmd/job_log.go
  app/cmd/job_param.go
  app/cmd/job_search.go
  app/cmd/job_stop.go
  app/cmd/job_stop_test.go
  app/cmd/job_type.go
  app/cmd/open.go
  app/cmd/plugin_check.go
  app/cmd/plugin_install.go
  app/i18n/jcli/zh_CN/LC_MESSAGES/jcli.po
  client/job.go
  client/job_test.go
Labels: feature

#249 Add param-entry for job build
  app/cmd/job_build.go
  app/cmd/job_build_test.go
  app/cmd/restart_test.go
  app/cmd/root.go
  client/common.go
  client/common_test.go
Labels: feature

#251 Add support to use update center mirror
  app/cmd/center_mirror.go
  app/cmd/center_mirror_test.go
  app/cmd/config_add.go
  app/cmd/doctor.go
  app/cmd/doctor_test.go
  app/cmd/job_create_test.go
  app/health/core.go
  app/health/core_test.go
  app/health/setup_test.go
  app/i18n/jcli/zh_CN/LC_MESSAGES/jcli.po
  client/updateCenter.go
  client/updateCenter_test.go
  client/updateCenter_test_common.go
Labels: feature

#253 Add sub shell support
  app/cmd/config.go
  app/cmd/config_select.go
  app/cmd/job_type_test.go
  app/cmd/root.go
  app/cmd/shell.go
  app/i18n/jcli/zh_CN/LC_MESSAGES/jcli.po
  go.mod
  go.sum
Labels: feature

#255 Add support to create a plugin
  app/cmd/plugin_create.go
  app/i18n/jcli/zh_CN/LC_MESSAGES/jcli.po
Labels: feature

#261 Add badge of docker pull
  README-zh.md
  README.md
Labels: chore

#259 Add support to list Jenkins agents
  app/cmd/computer.go
  app/cmd/computer_list.go
  app/cmd/computer_list_test.go
  app/i18n/jcli/zh_CN/LC_MESSAGES/jcli.po
  client/computer.go
  client/computer_test.go
  client/computer_test_common.go
Labels: feature

#262 Add support to run Jenkins
  app/cmd/center_download.go
  app/cmd/center_download_test.go
  app/cmd/center_start.go
  app/cmd/center_start_test.go
  app/i18n/jcli/zh_CN/LC_MESSAGES/jcli.po
Labels: feature

#264 Add other ways to download jcli
  Dockerfile-darwin
  Dockerfile-win
  Makefile
  README-zh.md
  README.md
  client/casc.go
Labels: documentation
