Repository jenkins-zh/jenkins-cli, pull requests merged in 2019-12, with the labels that each got.

#263 Add comment for Develop Environment
  CONTRIBUTING.md
Labels: documentation

#267 Add support to download the latest dev version of jcli
  Docker-dev
  Makefile
  README-zh.md
  README.md
Labels: feature

#268 Make jcli docker dev image be smaller
  .github/workflows/dev-image.yaml
  Docker-dev
  Dockerfile-dev
  Makefile
  README-zh.md
  README.md
Labels: chore

#275 Support give system property to jenkins.war
  app/cmd/center_start.go
Labels: feature

#274 Support cancel multiple queue item one time
  app/cmd/queue_cancel.go
  app/cmd/queue_cancel_test.go
Labels: feature

#272 Add test cases for open commands
  app/cmd/casc_apply.go
  app/cmd/casc_export.go
  app/cmd/casc_open.go
  app/cmd/casc_open_test.go
  app/cmd/casc_reload.go
  app/cmd/casc_schema.go
  app/cmd/center.go
  app/cmd/center_mirror.go
  app/cmd/center_start.go
  app/cmd/center_start_test.go
  app/cmd/common.go
  app/cmd/computer_list.go
  app/cmd/config.go
  app/cmd/crumbIssuer.go
  app/cmd/job_artifact.go
  app/cmd/job_artifact_download.go
  app/cmd/job_build.go
  app/cmd/job_create.go
  app/cmd/job_delete.go
  app/cmd/job_edit.go
  app/cmd/job_history.go
  app/cmd/job_input.go
  app/cmd/job_log.go
  app/cmd/job_param.go
  app/cmd/job_search.go
  app/cmd/job_stop.go
  app/cmd/job_type.go
  app/cmd/job_type_test.go
  app/cmd/open.go
  app/cmd/open_test.go
  app/cmd/plugin_check.go
  app/cmd/plugin_install.go
  app/cmd/plugin_list.go
  app/cmd/plugin_open.go
  app/cmd/plugin_open_test.go
  app/cmd/plugin_search.go
  app/cmd/plugin_uninstall.go
  app/cmd/plugin_upgrade.go
  app/cmd/plugin_upgrade_test.go
  app/cmd/plugin_upload.go
  app/cmd/queue_cancel.go
  app/cmd/queue_list.go
  app/cmd/restart.go
  app/cmd/user.go
  app/cmd/user_create.go
  app/cmd/user_delete.go
  app/cmd/user_token.go
  app/i18n/jcli/zh_CN/LC_MESSAGES/jcli.po
  util/cmd.go
  util/cmd_test.go
Labels: tests

#271 Remove url in the markdown template
  app/cmd/doc.go
Labels: chore

#273 Add support for color the output
  .travis.yml
  Makefile
  app/cmd/job_history.go
  app/cmd/job_history_test.go
  go.mod
  go.sum
  util/color.go
  util/color_test.go
Labels: feature

#276 Add support to release a plugin
  app/cmd/center_start.go
  app/cmd/center_start_test.go
  app/cmd/common.go
  app/cmd/plugin_create.go
  app/cmd/plugin_create_test.go
  app/cmd/plugin_release.go
  app/cmd/plugin_release_test.go
  util/cmd.go
Labels: feature

#266 Add support to manage credentials
  app/cmd/common.go
  app/cmd/credential.go
  app/cmd/credential_create.go
  app/cmd/credential_create_test.go
  app/cmd/credential_delete.go
  app/cmd/credential_delete_test.go
  app/cmd/credential_list.go
  app/cmd/credential_list_test.go
  client/credentials.go
  client/credentials_test.go
  client/credentials_test_common.go
Labels: feature

#278 Add more cmds for agent
  app/cmd/computer_launch.go
  app/cmd/computer_launch_test.go
  app/cmd/computer_list.go
  app/cmd/computer_log.go
  app/cmd/computer_log_test.go
  client/computer.go
  client/computer_test.go
  client/computer_test_common.go
Labels: feature

#280 Add diagnose for casc cmd
  app/cmd/casc.go
  app/cmd/casc_test.go
  app/cmd/job_build_test.go
  app/cmd/job_history.go
  app/cmd/job_history_test.go
  app/cmd/root.go
  app/cmd/root_test.go
  app/health/core.go
  app/health/core_test.go
  client/pluginManager_test_common.go
  client/test_methods.go
Labels: feature

#281 Add support to search Jenkins job or folder
  app/cmd/casc.go
  app/cmd/job_search.go
  app/cmd/job_search_test.go
  app/cmd/plugin.go
  app/cmd/root.go
  client/job.go
  client/job_test.go
  client/job_test_common.go
  client/pluginManager_test_common.go
  client/pluginManger.go
  go.mod
  go.sum
Labels: feature

#282 Fix a typo in PO file
  app/i18n/jcli/zh_CN/LC_MESSAGES/jcli.po
Labels: bugfix

#284 Enhance the searching Jenkins job
  app/cmd/casc.go
  app/cmd/casc_apply.go
  app/cmd/casc_export.go
  app/cmd/casc_open.go
  app/cmd/casc_reload.go
  app/cmd/casc_schema.go
  app/cmd/casc_test.go
  app/cmd/common.go
  app/cmd/common_test.go
  app/cmd/credential.go
  app/cmd/credential_create.go
  app/cmd/credential_delete.go
  app/cmd/credential_list.go
  app/cmd/job_search.go
  app/cmd/job_search_test.go
  app/cmd/plugin_create.go
  app/cmd/plugin_release.go
  client/job.go
  util/reflect.go
Labels: feature

#285 Improve the data output from cmd
  app/cmd/common.go
  app/cmd/computer_list.go
  app/cmd/config_list.go
  app/cmd/config_list_test.go
  app/cmd/credential_list.go
  app/cmd/credential_list_test.go
  app/cmd/job_history.go
  app/cmd/job_history_test.go
  app/cmd/job_search.go
  app/cmd/plugin_list.go
  app/cmd/plugin_list_test.go
  app/cmd/queue_list.go
  app/cmd/queue_list_test.go
  client/computer_test.go
  client/computer_test_common.go
Labels: feature

#290 Add support to create a jnlp agent
  app/cmd/common.go
  app/cmd/computer_create.go
  app/cmd/computer_create_test.go
  app/cmd/computer_delete.go
  app/cmd/computer_delete_test.go
  app/cmd/computer_launch.go
  app/cmd/computer_launch_test.go
  app/cmd/credential_delete.go
  app/cmd/job_delete.go
  app/cmd/user_delete.go
  client/computer.go
  client/computer_test.go
  client/computer_test_common.go
Labels: feature

#289 Add support to create a new token for other users
  app/cmd/center_start.go
  app/cmd/user_token.go
  app/cmd/user_token_test.go
  client/user.go
  client/user_test.go
  client/user_test_common.go
Labels: feature

#291 Add support take url from cmd line options
  app/cmd/common.go
  app/cmd/computer.go
  app/cmd/computer_create.go
  app/cmd/computer_delete.go
  app/cmd/computer_launch.go
  app/cmd/computer_list.go
  app/cmd/computer_log.go
  app/cmd/config.go
  app/cmd/config_generate.go
  app/cmd/config_generate_test.go
  app/cmd/root.go
  app/cmd/root_test.go
  client/common.go
  util/http.go
Labels: feature

#292 Add support get the identity of Jenkins
  .github/PULL_REQUEST_TEMPLATE.md
  app/cmd/center_identity.go
  app/cmd/center_identity_test.go
  app/cmd/center_upgrade.go
  client/core.go
  client/core_test.go
  client/core_test_common.go
Labels: feature

#294 Fix the bash completion error which caused by refactoring
  app/cmd/common.go
  app/cmd/common_test.go
  app/cmd/plugin_list_test.go
  app/cmd/root.go
  app/cmd/shell.go
Labels: bugfix

#293 Fix the warning which found by lgtm.com
  app/cmd/plugin_search.go
  app/cmd/shell.go
  app/cmd/shell_test.go
  util/cmd.go
  util/cmd_test.go
Labels: bugfix

#296 Add zsh and powerShell completion support
  app/cmd/completion.go
  app/cmd/completion_test.go
  util/logger.go
Labels: feature
