Repository jenkins-zh/jenkins-cli, pull requests merged in 2019-09, with the labels that each got.

#137 Add support to output installed plugins as json format
  app/cmd/common.go
  app/cmd/plugin_list.go
  app/cmd/plugin_list_test.go
  client/pluginManager_test.go
  client/test_methods.go
Labels: feature

#139 Fix the issue that cannot uninstall pluing
  app/cmd/plugin_uninstall.go
  app/cmd/plugin_uninstall_test.go
  client/common_test.go
  client/pluginManager_test.go
  client/pluginManger.go
  client/test_methods.go
  sonar-project.properties
Labels: bugfix

#140 Add post command hook
  app/cmd/common.go
  app/cmd/config.go
  app/cmd/plugin_upload.go
  app/cmd/plugin_upload_test.go
  app/cmd/root.go
  app/cmd/root_test.go
  client/common.go
  client/job.go
  client/pluginManager_test.go
  client/pluginManger.go
  client/requestmatcher.go
  client/test_methods.go
Labels: feature

#141 Add support to finish the watch by conditions
  app/cmd/center.go
  app/cmd/center_watch.go
  app/cmd/center_watch_test.go
  app/cmd/common.go
Labels: feature

#143 Add support to search all jobs
  app/cmd/job_search.go
  app/cmd/job_search_test.go
  client/job.go
  client/job_test.go
Labels: feature

#146 Try to fix the travis pr id
  .travis.yml
Labels: bugfix

#149 Add user-agent into http request
  app/setup_test.go
  app/version.go
  app/version_test.go
  client/common.go
Labels: chore

#144 Add support to upgrade a plugin by command
  app/cmd/plugin_upgrade.go
  app/cmd/plugin_upgrade_test.go
  client/pluginManager_test.go
  client/pluginManger.go
  client/test_methods.go
  go.mod
  go.sum
Labels: feature

#157 Set the exit code for golint
  Makefile
Labels: chore

#162 Add contribution guide
  CONTRIBUTING.md
  README-zh.md
  README.md
Labels: documentaion

#158 Add sonar code coverage report paths config item
  sonar-project.properties
Labels: chore

#161 Add bash completion for jcli
  app/cmd/completion.go
  app/cmd/completion_test.go
Labels: feature

#163 Add single name as a output format
  app/cmd/job_search.go
  app/cmd/job_search_test.go
Labels: feature

#156 Show the version of plugins when searching
  app/cmd/plugin_search.go
  app/cmd/plugin_search_test.go
  client/pluginManager_test.go
  client/test_methods.go
  client/updateCenter.go
  client/updateCenter_test.go
Labels: feature

#168 Add two badges which are all releases and code size
  README-zh.md
  README.md
Labels: chore

#171 Add a new label which is hacktoberfest
  .github/settings.yml
Labels: no-changelog
