Repository jenkins-zh/jenkins-cli, pull requests merged in 2019-08, with the labels that each got.

#96 Generate sha256 text file
  Makefile
  release.sh
Labels: chore

#95 Add suppor to build a job with params in batch mode
  app/cmd/job_build.go
  app/cmd/job_param.go
  client/job.go
Labels: feature

#97 Fix the error output when restarting Jenkins
  client/core.go
Labels: bug-fix

#99 Add document to describe how to manage the plugins
  README.md
  doc/README.md
Labels: documentatioin

#102 fix remove a config
  app/cmd/config.go
  app/cmd/config_remove.go
Labels: bugfix

#103 add Issue template
  .github/ISSUE_TEMPLATE/issues_start.md
Labels: chore

#101 Add support to add description for the jcli config item
  app/cmd/config.go
  app/cmd/config_add.go
  app/cmd/config_list.go
Labels: feature

#105 Use constant instead of duplicating literal
  client/job.go
  client/user.go
  util/http.go
Labels: chore

#106 Add nest comment for a empty method
  client/pluginManger.go
Labels: chore

#107 fix sonar check unused parameters
  app/cmd/center.go
  app/cmd/config.go
  app/cmd/config_add.go
  app/cmd/config_edit.go
  app/cmd/config_generate.go
  app/cmd/config_list.go
  app/cmd/config_remove.go
  app/cmd/config_select.go
  app/cmd/crumbIssuer.go
  app/cmd/job.go
  app/cmd/job_type.go
  app/cmd/open.go
  app/cmd/plugin.go
  app/cmd/plugin_check.go
  app/cmd/plugin_install.go
  app/cmd/plugin_list.go
  app/cmd/plugin_open.go
  app/cmd/plugin_upload.go
  app/cmd/queue.go
  app/cmd/restart.go
  app/cmd/root.go
  app/cmd/user.go
  app/cmd/user_edit.go
  app/cmd/user_token.go
  client/user.go
  util/http.go
Labels: chore

#110 Fix download plugin failure
  client/pluginApi.go
Labels: bugfix

#111 Fix certificate issue when downing plugins
  client/pluginApi.go
Labels: bugfix

#112 Add Jenkinsfile with build stage
  Jenkinsfile
Labels: chore

#113 Add test cases for password util
  Jenkinsfile
  util/password.go
  util/password_test.go
  util/setup_test.go
Labels: chore

#109 Fix search plugin result inaccurate
  app/cmd/plugin_search.go
Labels: bugfix

#108 Update issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/issues_start.md
Labels: chore

#118 Remove redundant blank words
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/settings.yml
Labels: bugfix, no-changelog

#114 Fix the error when install a plugin
  client/pluginManager_test.go
  client/pluginManger.go
  client/setup_test.go
Labels: bugfix

#117 Add support for cmd pre hook
  .gitignore
  Jenkinsfile
  Makefile
  app/cmd/config.go
  app/cmd/plugin_upload.go
  app/cmd/root.go
  app/cmd/root_test.go
  app/cmd/setup_test.go
  util/setup_test.go
Labels: feature

#116 Add a global Jenkins name option
  app/cmd/center.go
  app/cmd/config_edit.go
  app/cmd/job_build.go
  app/cmd/job_create.go
  app/cmd/job_delete.go
  app/cmd/job_edit.go
  app/cmd/job_history.go
  app/cmd/job_log.go
  app/cmd/job_param.go
  app/cmd/job_search.go
  app/cmd/job_stop.go
  app/cmd/job_type.go
  app/cmd/plugin_check.go
  app/cmd/plugin_install.go
  app/cmd/plugin_list.go
  app/cmd/plugin_open.go
  app/cmd/plugin_search.go
  app/cmd/plugin_uninstall.go
  app/cmd/plugin_upload.go
  app/cmd/queue.go
  app/cmd/restart.go
  app/cmd/root.go
  app/cmd/user.go
  app/cmd/user_create.go
  app/cmd/user_delete.go
  app/cmd/user_edit.go
  app/cmd/user_token.go
Labels: feature

#122 Add support to copy binary file to system path
  Makefile
Labels: chore

#125 Use shared-library to super container dsl
  Jenkinsfile
Labels: chore

#120 WIP: Fix mess up the table output when words are not English
  util/padding.go
  util/padding_test.go
  util/table.go
  util/table_test.go
Labels: bugfix

#127 Add travis and sonar project property file
  .travis.yml
  Makefile
  sonar-project.properties
Labels: chore

#123 Add support to upgrade Jenkins
  app/cmd/center.go
  app/cmd/center_upgrade.go
  app/cmd/center_watch.go
  client/updateCenter.go
  go.mod
  go.sum
Labels: feature

#128 Add more testcases
  README-zh.md
  README.md
  app/cmd/config_test.go
  app/cmd/plugin_upload.go
  app/cmd/root.go
  app/cmd/root_test.go
  sonar-project.properties
  util/table_test.go
Labels: chore

#124 Add support to define a suite of plugins
  app/cmd/config.go
  app/cmd/config_test.go
  app/cmd/plugin.go
  app/cmd/plugin_install.go
  go.mod
  go.sum
Labels: feature

#129 Add support to download Jenkins
  .gitignore
  .travis.yml
  Jenkinsfile
  Makefile
  app/cmd/center.go
  app/cmd/center_download.go
  app/cmd/center_download_test.go
  app/cmd/center_test.go
  app/cmd/center_upgrade.go
  app/cmd/center_upgrade_test.go
  app/cmd/center_watch.go
  app/cmd/center_watch_test.go
  app/cmd/common.go
  app/cmd/config.go
  app/cmd/root.go
  client/common.go
  client/updateCenter.go
  client/updateCenter_test.go
  mock/mhttp/roundtripper.go
  sonar-project.properties
  util/http.go
  util/http_test.go
Labels: feature
