Repository jenkins-zh/jenkins-cli, pull requests merged in 2019-10, with the labels that each got.

#177 Add a stargazers over time chart
  README-zh.md
  README.md
Labels: no-changelog

#173 Add git backup actions
  .github/workflow/backup.yaml
  CONTRIBUTING.md
Labels: Hacktoberfest, chore

#164 Add support to input pipeline job
  app/cmd/job_input.go
  app/cmd/job_input_test.go
  client/job.go
  client/job_test.go
  client/job_test_common.go
  client/test_methods.go
  go.mod
Labels: feature

#180 Add test cases for jenkins user client
  .github/workflows/backup.yaml
  client/test_methods.go
  client/user.go
  client/user_test.go
  client/user_test_common.go
Labels: Hacktoberfest, chore

#178 Remove the unnecessary code lines
  app/cmd/plugin_trend.go
  app/cmd/plugin_trend_test.go
  client/common.go
  client/pluginApi.go
  client/pluginApi_test.go
  client/pluginApi_test_common.go
  client/pluginManager_test.go
  client/pluginManger.go
  client/test_methods.go
  util/collect.go
  util/collect_test.go
Labels: Hacktoberfest, no-change-log

#174 Add a command to generate the whole documents for jcli
  app/cmd/doc.go
  app/cmd/doc_test.go
  go.sum
Labels: Hacktoberfest, feature

#181 Add test cases for user command
  app/cmd/user.go
  app/cmd/user_create.go
  app/cmd/user_create_test.go
  app/cmd/user_delete.go
  app/cmd/user_delete_test.go
  app/cmd/user_test.go
  app/cmd/user_token.go
  app/cmd/user_token_test.go
  client/test_methods.go
  client/user_test_common.go
Labels: Hacktoberfest, no-changelog

#184 Bind build status with quality gate result
  .travis.yml
Labels: Hacktoberfest, chore

#186 Fix issue where version was not printed even though -v flag was passed
  app/cmd/root.go
Labels: Hacktoberfest

#187 Add permission information for request
  client/common.go
  client/common_test.go
Labels: Hacktoberfest, bugfix

#185 Add support to download artifacts
  .travis.yml
  app/cmd/job_artifact.go
  app/cmd/job_artifact_download.go
  app/cmd/job_artifact_download_test.go
  app/cmd/job_artifact_test.go
  client/artifacts.go
  client/artifacts_test.go
  client/artifacts_test_common.go
  client/common.go
  util/http.go
  util/http_test.go
Labels: Hacktoberfest, enhancement

#188 Add jcli completion description
  app/cmd/completion.go
Labels: Hacktoberfest, chore

#189 Fix the wrong description of completion command
  app/cmd/completion.go
Labels: no-changelog

#194 Add language links into readmefile
  README-zh.md
  README.md
Labels: documentation

#199 Add git ignore files for idea
  .gitignore
Labels: Hacktoberfest, chore

#190 Add test cases for job client
  .travis.yml
  Makefile
  app/cmd/center.go
  app/cmd/center_download.go
  app/cmd/center_download_test.go
  app/cmd/center_watch.go
  app/cmd/job_artifact_download_test.go
  app/cmd/job_delete_test.go
  app/cmd/job_input_test.go
  app/cmd/restart.go
  app/cmd/restart_test.go
  app/cmd/root.go
  app/cmd/root_test.go
  app/cmd/user_create.go
  app/cmd/user_create_test.go
  app/cmd/user_delete_test.go
  app/cmd/user_token_test.go
  client/common.go
  client/core.go
  client/core_test.go
  client/core_test_common.go
  client/job.go
  client/job_test.go
  client/job_test_common.go
  client/pluginManager_test.go
  client/requestmatcher.go
  client/requestmatcher_test.go
  client/status.go
  client/status_test.go
  client/status_test_common.go
  client/test_methods.go
  client/updateCenter.go
  client/updateCenter_test.go
  client/user.go
  client/user_test.go
  client/user_test_common.go
  go.mod
  go.sum
  util/http.go
Labels: Hacktoberfest, chore

#203 Add dependencies as a label
  .github/release-drafter.yml
  .github/settings.yml
Labels: chore

#205 Add support to create a job by copy mode
  app/cmd/config.go
  app/cmd/doc.go
  app/cmd/doc_test.go
  app/cmd/job_artifact.go
  app/cmd/job_artifact_download.go
  app/cmd/job_artifact_download_test.go
  app/cmd/job_build.go
  app/cmd/job_create.go
  app/cmd/job_create_test.go
  app/cmd/job_delete.go
  app/cmd/job_log.go
  app/cmd/job_stop.go
  app/cmd/job_type.go
  app/cmd/job_type_test.go
  app/cmd/plugin_download.go
  app/cmd/plugin_search.go
  app/cmd/plugin_uninstall.go
  app/cmd/queue_cancel.go
  app/cmd/queue_cancel_test.go
  app/cmd/user_create.go
  app/cmd/user_create_test.go
  app/cmd/user_delete.go
  app/cmd/user_delete_test.go
  client/job.go
  client/job_test.go
  client/test_methods.go
Labels: Hacktoberfest, feature

#201 Add badge for godoc
  README-zh.md
  README.md
Labels: Hacktoberfest

#208 Add documentation for scoop
  README-zh.md
  README.md
Labels: Hacktoberfest, documentation

#210 Fixes and additions to the README text to improve UX.
  README.md
Labels: Hacktoberfest, documentation

#209 Add documentation for JetBrains open source license
  README-zh.md
  README.md
  goland.svg
Labels: Hacktoberfest, documentaion, documentation

#212 Add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Hacktoberfest, chore

#183 Add language setting with the api request
  app/cmd/config.go
  app/cmd/config_generate.go
  app/cmd/root.go
  client/common.go
  client/common_test.go
Labels: Hacktoberfest, enhancement
