Repository jenkins-zh/jenkins-cli, pull requests merged in 2020-04, with the labels that each got.

#376 Fix: doc command no need config
  app/cmd/root.go
Labels: bugfix

#375 Fix the wrong tips of job log command
  .github/workflows/pull-request.yaml
  .gitignore
  .travis.yml
  Makefile
  app/cmd/center_download_test.go
  app/cmd/center_start_test.go
  app/cmd/computer_list.go
  app/cmd/job_build_test.go
  app/cmd/job_history.go
  app/cmd/job_history_test.go
  app/cmd/job_log.go
  app/cmd/queue_test.go
  app/cmd/root.go
  app/cmd/root_test.go
  app/cmd/shell_test.go
  app/cmd/user_delete_test.go
  app/cmd/user_edit_test.go
  app/cmd/version_test.go
  go.mod
  go.sum
  util/color.go
  util/color_test.go
Labels: fix

#377 Add support to open browser with a specific one
  Dockerfile-darwin
  Dockerfile-dev
  Dockerfile-win
  Makefile
  app/cmd/casc_open.go
  app/cmd/common.go
  app/cmd/open.go
  app/cmd/plugin_open.go
  util/cmd.go
  util/cmd_test.go
Labels: feature

#378 Add auto completion support for plugin upload
  app/cmd/plugin_upload.go
Labels: feature

#382 Add man page support
  app/cmd/doc.go
Labels: feature

#380 Add auto completion for jcli center start
  app/cmd/center_start.go
Labels: feature

#384 Add support to open external link
  app/cmd/config.go
  app/cmd/config_generate_test.go
  app/cmd/open.go
Labels: feature

#388 Add date as part of version print
  .goreleaser.yml
  app/cmd/version.go
  app/version.go
Labels: feature

#393 Fix the broken links in readme file
  README-zh.md
  README.md
Labels: chore

#392 Commnd documentation improments
  Makefile
  app/cmd/casc_open.go
  app/cmd/completion.go
  app/cmd/open.go
  app/cmd/plugin_open.go
Labels: documentation

#301 Add integration tests
  .github/workflows/backup.yaml.md
  .github/workflows/dev-image.yaml
  .github/workflows/int-test-darwin.yaml
  .github/workflows/int-test-ubuntu.yaml
  Makefile
  app/cmd/casc_apply.go
  app/cmd/center_start.go
  app/cmd/config_list.go
  app/cmd/credential_create.go
  app/cmd/crumbIssuer.go
  app/cmd/plugin_download.go
  app/cmd/queue_list.go
  app/cmd/root.go
  client/common.go
  client/common_test.go
  client/pluginApi.go
  e2e/common.go
  e2e/completion_test.go
  e2e/computer_test.go
  e2e/config_test.go
  e2e/crumb_test.go
  e2e/doc_test.go
  e2e/job_test.go
  e2e/plugin_test.go
  e2e/queue_test.go
  e2e/root_test.go
  e2e/setup_test.go
  e2e/withdependencies/casc_test.go
  e2e/withdependencies/credential_test.go
  e2e/withdependencies/job_test.go
  e2e/withdependencies/setup_test.go
  go.mod
  go.sum
Labels: test

#383 Add support to clean invalid config item
  app/cmd/center_download_test.go
  app/cmd/center_test.go
  app/cmd/center_upgrade_test.go
  app/cmd/center_watch_test.go
  app/cmd/computer_launch_test.go
  app/cmd/config_clean.go
  app/cmd/cwp_test.go
  app/cmd/job_artifact_download_test.go
  app/cmd/job_build_test.go
  app/cmd/job_delete_test.go
  app/cmd/job_edit_test.go
  app/cmd/job_stop_test.go
  app/cmd/job_type_test.go
  app/helper/error.go
  app/helper/error_test.go
  client/artifacts_test_common.go
  client/common.go
  client/common_test.go
  client/common_test_common.go
  client/computer_test_common.go
  client/core_test_common.go
  client/credentials_test_common.go
  client/job_test.go
  client/job_test_common.go
  client/pluginApi_test_common.go
  client/pluginManager_test.go
  client/status_test_common.go
  client/test_methods.go
  client/updateCenter_test.go
  client/user_test_common.go
  util/http_test.go
Labels: feature
