Repository jenkins-zh/jenkins-cli, pull requests merged in 2020-11, with the labels that each got.

#458 Support export current Jenkins as a formula
  .github/workflows/pull-request.yaml
  .github/workflows/sonarqube.yaml.bak
  Makefile
  app/cmd/center_download.go
  app/cmd/common/cmd_valid.go
  app/cmd/common/version_since.go
  app/cmd/cwp.go
  app/cmd/plugin_formula.go
  app/cmd/plugin_formula_test.go
  app/cmd/runner_test.go
  client/common.go
  client/pluginManger.go
  go.mod
  go.sum
Labels: feature

#461 Add documentation for more package manager
  README.md
Labels: documentation

#462 Add an option to print cwp version
  app/cmd/cwp.go
  go.sum
Labels: feature

#414 Add http proxy support which can ready from env variable
  app/cmd/center_start.go
  app/cmd/plugin_upload.go
  client/common.go
  util/env.go
  util/http.go
Labels: enhancement

#465 Add support to download a plugin with specific version
  .github/workflows/backup.yaml
  app/cmd/plugin_download.go
  client/pluginApi.go
  client/pluginManger.go
Labels: feature

#464 Add support to run docker image with center start cmd
  .github/workflows/release.yaml
  app/cmd/center_start.go
  client/pluginApi.go
  docs/book/en/download.md
  docs/book/zh/download.md
Labels: feature

#467 Add another similar project jenkins-job-cli
  README.md
Labels: chore, no-changelog

#469 Add support fetch Jenkins token automatically
  Makefile
  app/cmd/center_login.go
  app/cmd/center_start.go
  app/cmd/condition/plugin_dep.go
  app/cmd/config/root.go
  app/cmd/config/uninstall_plugin.go
  app/cmd/config_plugin.go
  app/cmd/cwp.go
  app/cmd/doc.go
  app/cmd/plugin_install.go
  app/cmd/root.go
  client/pluginManger.go
  client/user.go
  go.mod
  util/net.go
Labels: feature

#472 Fix the wrong path of config plugin
  app/cmd/center_login.go
  app/cmd/center_start.go
  app/cmd/center_watch.go
  app/cmd/common/completion.go
  app/cmd/common/plugin.go
  app/cmd/computer.go
  app/cmd/computer_delete.go
  app/cmd/computer_launch.go
  app/cmd/computer_log.go
  app/cmd/config.go
  app/cmd/config/completion.go
  app/cmd/config/fetch.go
  app/cmd/config/install.go
  app/cmd/config/list.go
  app/cmd/config/root.go
  app/cmd/config/type.go
  app/cmd/config/uninstall.go
  app/cmd/config_data.go
  app/cmd/config_generate.go
  app/cmd/config_plugin.go
  app/cmd/config_remove.go
  app/cmd/config_select.go
  app/cmd/open.go
  app/cmd/root.go
Labels: bugfix

#474 added checking of the 'current' option in the config file
  app/cmd/config.go
Labels: bugfix

#475 Move casc sub-command into jcli-casc-plugin
  .github/dependabot.yml
  .github/workflows/backup.yaml
  .github/workflows/pull-request.yaml
  .github/workflows/release.yaml
  .goreleaser.yml
  Makefile
  README-zh.md
  README.md
  app/cmd/casc.go
  app/cmd/casc_apply.go
  app/cmd/casc_apply_test.go
  app/cmd/casc_export.go
  app/cmd/casc_export_test.go
  app/cmd/casc_open.go
  app/cmd/casc_open_test.go
  app/cmd/casc_reload.go
  app/cmd/casc_reload_test.go
  app/cmd/casc_schema.go
  app/cmd/casc_schema_test.go
  app/cmd/casc_test.go
  app/cmd/center_login.go
  app/cmd/config/root.go
  app/cmd/config_edit.go
  app/cmd/plugin_open.go
  app/cmd/restart.go
  app/cmd/root.go
  app/cmd/root_test.go
  app/cmd/shutdown.go
  e2e/withdependencies/casc_test.go
Labels: enhancement, feature
