Repository jenkins-zh/jenkins-cli, pull requests merged in 2020-02, with the labels that each got.

#313 Add download details link into readme file
  README-zh.md
  README.md
Labels: no-changelog

#314 Add golang module proxy setting documentation
  CONTRIBUTING.md
Labels: no-changelog

#258 Add support upgrade all plugins
  app/cmd/plugin_upgrade.go
  app/cmd/plugin_upgrade_test.go
  client/pluginApi.go
  client/pluginApi_test.go
  client/pluginApi_test_common.go
Labels: enhancement, need-to-fix, need-to-test

#317 Fix the incorrect download doc link in README-zh.md
  README-zh.md
Labels: no-changelog

#312 Add documentation for support Chocolatey
  README-zh.md
  README.md
Labels: documentation

#321 Add snapcraft support
  .gitignore
  README-zh.md
  README.md
  app/cmd/shell_test.go
  snapcraft.yaml
Labels: documentation

#325 Fix that cannot create credentials
  app/cmd/credential_create.go
  app/cmd/credential_create_test.go
  client/common.go
  client/credentials.go
  client/credentials_test.go
Labels: bugfix

#322 Fix cannot start a non-lts jenkins server
  app/cmd/center_download.go
  app/cmd/center_start.go
Labels: bugfix

#327 Support search job by parent name
  app/cmd/job_search.go
  client/doc/README-zh.md
  client/doc/README.md
  client/job.go
  client/job_test_common.go
Labels: feature

#328 Show the changelog of jcli
  app/cmd/computer_list.go
  app/cmd/computer_list_test.go
  app/cmd/config_generate_test.go
  app/cmd/config_list_test.go
  app/cmd/doc_test.go
  app/cmd/job_stop_test.go
  app/cmd/queue_test.go
  app/cmd/root.go
  app/cmd/root_test.go
  app/cmd/user_token_test.go
  app/cmd/version.go
  app/cmd/version_test.go
  app/version.go
  client/release.go
  client/release_test.go
  client/release_test_common.go
  go.mod
  go.sum
Labels: feature

#335 Add bilibili as a sponsor account
  .github/FUNDING.yml
Labels: no-changelog

#345 Add option to restart Jenkins directly
  .github/workflows/backup.yaml
  .github/workflows/pull-request.yaml
  .travis.yml
  Makefile
  app/cmd/restart.go
  app/cmd/restart_test.go
  client/core.go
  client/core_test.go
  client/core_test_common.go
Labels: feature
