Repository jenkins-zh/jenkins-cli, pull requests merged in 2021-08, with the labels that each got.

#588 add -tail to job log
  app/cmd/job_log.go
Labels: size/M

#610 Add a new function which creates a job in a folder
  client/job.go
Labels: size/XS

#617 Add config file for the GitHub codespaces
  .devcontainer/devcontainer.json
Labels: chore
