Repository jenkins-zh/jenkins-cli, pull requests merged in 2021-02, with the labels that each got.

#525 Fix the error usage of version
  .github/settings.yml
  .goreleaser.yml
Labels: bugfix, size/S

#527 Add MacPorts Documentation
  README.md
Labels: approved, kind/doc, lgtm

#529 Fix Jenkins agent launch in docker mode
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/e2e-test.yaml
  .github/workflows/int-test-darwin.yaml
  .github/workflows/int-test-ubuntu.yaml
  Makefile
  app/cmd/center_start.go
  app/cmd/computer_launch.go
  client/computer.go
  e2e/common.go
  e2e/computer_test.go
  e2e/setup_test.go
  e2e/withdependencies/setup_test.go
Labels: size/XXL

#530 Fix InsecureSkipVerify invalid
  app/cmd/root.go
  app/helper/error.go
Labels: kind/bug, size/XS
