Repository jenkins-zh/jenkins-cli, pull requests merged in 2021-03, with the labels that each got.

#541 Fix segfaults URL param
  util/url.go
Labels: kind/bugfix, size/XS

#547 Add support update config item token
  app/cmd/config.go
  app/cmd/config_update.go
Labels: enhancement, size/L

#545 Add an option for crumbIssue session id to center start command
  app/cmd/center_start.go
Labels: enhancement, size/XS

#548 Select the current Jenkins if the name is empty when update config
  app/cmd/config_update.go
Labels: enhancement, size/XS

#549 Revert "Fix segfaults URL param"
  util/url.go
Labels: bugfix, size/XS
